basic:
  name: "Chen Qihui"
  title: "Senior Java Developer"
  location: "Yuhang District, Hangzhou"
  email: "zjhzcqh@163.com"
  github: "https://github.com/zjhzcqh"
  linkedin: ""
  phone: "+86 13588307742"
  resumeLink: "resume/Chen-Qihui-Resume-EN.pdf"
  roles:
    - "Senior Java Developer"
    - "Microservices Architect"
    - "Backend Developer"
    - "Technology Enthusiast"
    - "Open Source Contributor"

about:
  description: "I am an experienced Senior Java Developer specializing in enterprise application development and microservices architecture design. I am proficient with the Spring ecosystem, distributed system design, and big data processing technologies. In my free time, I enjoy studying new technologies, contributing to open-source projects, and continuously improving my technical skills through practical experiences."
  skills:
    - "Java"
    - "Spring Framework"
    - "Microservices Architecture"
    - "Data Structures & Algorithms"
    - "Distributed Systems"
    - "Caching Architecture"
    - "Message Queues"
    - "Database Management"
    - "Linux Commands"
    - "Web Development"
    - "Golang"
    - "Python"

experience:
  - company: "HRG"
    position: "Senior Java Developer"
    period: "2023.11 - Present"
    logo: ""
    description:
      - "Participated in building Caicai's global HR system from scratch, developing the main data module for international expansion, establishing data centers in North America, Europe, and Singapore, supporting HR operations in multiple regions including the US, Germany, France, UK, Spain, Poland, Thailand, Malaysia, and Philippines."
      - "Established synchronization mechanisms for data and messages between domestic and overseas systems using Alibaba DTS tasks and scheduled scripts to ensure consistency and timely updates while ensuring compliance."
      - "Implemented multi-timezone handling strategies for logical and fixed dates, storing timestamps in databases and dynamically converting them based on user time zones to enhance user experience."
      - "Built an efficient permission management framework using AOP for permission judgment and filtering, supporting sub-department permissions, and encapsulated it into annotations to simplify the development process."

  - company: "Vehicle Data Platform"
    position: "Senior Java Developer"
    period: "2023.05 - 2023.11"
    logo: ""
    description:
      - "Led the design of the platform's internationalization solution, including multi-language support, multi-timezone data querying and exporting, and cross-regional secure data access. Developed and deployed the European version of the vehicle data platform, optimizing query and export logic to significantly improve user experience and system efficiency."
      - "Developed a user SDK to efficiently integrate Geely's multi-user platform, reducing project integration costs and enhancing user permission management. Introduced multi-service log tracing IDs and thread pool alarm strategies to improve fault diagnosis capabilities and system stability, ensuring high-performance operation."

  - company: "Webex"
    position: "Senior Java Developer"
    period: "2019.06 - 2023.01"
    logo: ""
    description:
      - "Responsible for the daily development and maintenance of multiple microservices (Thunder, Files, Avatar, Client-Logs, FeMO) in Content Service, including file security scanning, transcoding previews, upload/download management, avatar management, and client log management functions."
      - "Supplemented test cases to increase code coverage, optimized system features such as scheduled deletion of expired logs, enhanced pagination queries, optimized deadlocked thread monitoring, and handled OOM issues online, enhancing system stability and security."
      - "Designed and developed the Federation Migration Orchestrator, supporting the orchestration of data migration workflows across numerous microservices, effectively reducing team development time and costs."
      - "Participated in periodic Oncall tasks to ensure the safe and stable operation of online services, promptly responding to and resolving emergencies to guarantee service quality."

  - company: "Lvyue+"
    position: "Java Developer"
    period: "2017.08 - 2019.05"
    logo: ""
    description:
      - "Responsible for developing features such as surveys, registration systems, and community activities within the 'Lvyue+' app."
      - "Responsible for developing large-screen data displays, app-side user modules, and device center functionalities for the 'Smart Community' project."

education:
  - school: "Zhejiang University of Science and Technology"
    degree: "Bachelor's Degree"
    period: "2013.09 - 2017.06"
    major: "Information and Computational Science"
    description:
      - "Ranked in the top 15% of the major in comprehensive evaluation during university, received multiple scholarships, participated in student councils, and engaged in teaching support activities."

projects:
  - name: "Global HR System"
    description: "Participated in building Caicai's global HR system from scratch, developing the main data module for international expansion, establishing data centers in North America, Europe, and Singapore, supporting HR operations in multiple regions including the US, Germany, France, UK, Spain, Poland, Thailand, Malaysia, and Philippines."
    technologies: ["SpringBoot", "HSF", "Redis", "MySQL", "MetaQ"]
    period: "2023.11 - Present"
    responsibilities:
      - "Established synchronization mechanisms for data and messages between domestic and overseas systems using Alibaba DTS tasks and scheduled scripts to ensure consistency and timely updates while ensuring compliance."
      - "Implemented multi-timezone handling strategies for logical and fixed dates, storing timestamps in databases and dynamically converting them based on user time zones to enhance user experience."
      - "Built an efficient permission management framework using AOP for permission judgment and filtering, supporting sub-department permissions, and encapsulated it into annotations to simplify the development process."
    link: ""
    github: ""

  - name: "Vehicle Data Platform"
    description: "The Vehicle Data Platform processes massive amounts of ECU data reported by ZEEKR vehicles, providing M241 query, export, visualization capabilities, and remote diagnostics for vehicle engineers."
    technologies: ["SpringBoot", "Redis", "MySQL", "ClickHouse", "Kafka"]
    period: "2023.05 - 2023.11"
    responsibilities:
      - "Led the design of the platform's internationalization solution, including multi-language support, multi-timezone data querying and exporting, and cross-regional secure data access. Developed and deployed the European version of the vehicle data platform, optimizing query and export logic to significantly improve user experience and system efficiency."
      - "Developed a user SDK to efficiently integrate Geely's multi-user platform, reducing project integration costs and enhancing user permission management. Introduced multi-service log tracing IDs and thread pool alarm strategies to improve fault diagnosis capabilities and system stability, ensuring high-performance operation."
    link: ""
    github: ""

  - name: "Webex Files"
    description: "Webex provides high-quality video conferencing, online meetings, screen sharing, and message/file transfer services for businesses and individuals."
    technologies: ["SpringBoot", "PostgreSQL", "Redis", "Kafka", "Docker"]
    period: "2019.06 - 2023.01"
    responsibilities:
      - "Responsible for the daily development and maintenance of multiple microservices (Thunder, Files, Avatar, Client-Logs, FeMO) in Content Service, including file security scanning, transcoding previews, upload/download management, avatar management, and client log management functions."
      - "Supplemented test cases to increase code coverage, optimized system features such as scheduled deletion of expired logs, enhanced pagination queries, optimized deadlocked thread monitoring, and handled OOM issues online, enhancing system stability and security."
      - "Designed and developed the Federation Migration Orchestrator, supporting the orchestration of data migration workflows across numerous microservices, effectively reducing team development time and costs."
      - "Participated in periodic Oncall tasks to ensure the safe and stable operation of online services, promptly responding to and resolving emergencies to guarantee service quality."
    link: ""
    github: ""

certifications:
  - name: "Alibaba Coding Standard Certification"
    issuer: "Alibaba"
    date: "2023"

ui:
  nav:
    home: "Home"
    about: "About"
    experience: "Experience"
    projects: "Projects"
    education: "Education"
    certifications: "Certifications"
    contact: "Contact"
  hero:
    greeting: "Hello, I'm"
    intro: "I'm a"
    buttons:
      contact: "Contact Me"
      projects: "My Portfolio"
  about:
    title: "About Me"
    subtitle: "Who Am I?"
    story: "My Story"
    skills: "My Skills"
    button: "Contact Me"
  experience:
    title: "Work Experience"
    subtitle: "My Professional Journey"
  projects:
    title: "Portfolio"
    subtitle: "Recent Projects"
    buttons:
      view: "View Project"
      github: "GitHub"
  education:
    title: "Education"
    subtitle: "Academic Background"
  certifications:
    title: "Certifications"
    subtitle: "Professional Development"
  contact:
    title: "Contact Information"
    subtitle: "Get in Touch"
    email: "Email"
    phone: "Phone"
    location: "Location"
  footer:
    rights: "All Rights Reserved"
  lang:
    switch: "中文 / EN"
    resume: "Resume"